name = "flodesk-remote-mcp"
main = "src/index.ts"
compatibility_date = "2024-12-18"

[env.production]
name = "flodesk-remote-mcp"

[env.development]
name = "flodesk-remote-mcp-dev"

[durable_objects]
bindings = [
  { name = "SESSIONS", class_name = "SessionStorage" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "SessionStorage" ]

[[kv_namespaces]]
binding = "FLODESK_KV"
id = "01e45bfe15c34e24a3a4e0a0f4311593"
preview_id = "d09135afc6d94eb0b94207edb41c240d"